# Site settings
title: Alison Veit
email: contact@alisonveit.com
description: > # this means to ignore newlines until "baseurl:"
Alison Veit
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://alisonveit.com" # the base hostname & protocol for your site - used for feed.xml
twitter_username: justfouryou
github_username:  justfouryou

# Build settings
markdown: kramdown
